apiVersion: v1
kind: ConfigMap
metadata:
  name: recruithub-config
  namespace: recruithub
data:
  # Backend configuration
  DB_NAME: "recruitment_db"
  CORS_ORIGINS: "*"
  
  # MongoDB configuration
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  
  # Frontend configuration
  REACT_APP_BACKEND_URL: "http://your-domain.com/api"